### PR TITLE
added codes for multiple linear regression, added requested changes and committed them

### PR DESCRIPTION
**Pull request by parth-panchal**
added 2 code files:
- multiple linear regression using gradient descent and normal equation
- regularized multiple linear regression using gradient descent and normal equation

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @parth-panchal, amazing work. 
Please make specific folders for both and add a requirements.txt file as well for both the implementations.
For any queries. please feel free to reach out to us on our Slack channel. Thankyou :)

**Comment by parth-panchal** [comment]
I've made the necessary changes on my branch and committed them, however, I cannot see them reflected on GitHub and thus I am unable to create a pull request. Can you please look into that, I am fairly new with using Git? Thank you.

**Comment by parth-panchal** [comment]
> I've made the necessary changes on my branch and committed them, however, I cannot see them reflected on GitHub and thus I am unable to create a pull request. Can you please look into that, I am fairly new with using Git? Thank you.

Okay nevermind, I just learned that commits on the same branch in an open PR just get added on the previous unclosed one.

**Review by parth-panchal — COMMENTED** [review]
have made requested changes

**Pull request closed without merging**
