### PR TITLE
Added Face mask detector algorithm

### PR DESCRIPTION
**Pull request by sanjus-robotic-studio**
@geekquad please merge this PR

### CODE REVIEW

**Comment by sanjus-robotic-studio** [comment]
@geekquad please review this PR

**Review by geekquad — CHANGES_REQUESTED** [review]
All I can see is the dataset. I cannot see any algorithm.

**Comment by sanjus-robotic-studio** [comment]
It is in the python folder in a folder named as Face_Mask_Detector

**Comment by sanjus-robotic-studio** [comment]
@geekquad

**Comment by geekquad** [comment]
> It is in the python folder in a folder named as Face_Mask_Detector

Is it? Please delete it from the python folder and add it to the ML folder.

**Comment by sanjus-robotic-studio** [comment]
Ok will do

**Comment by sanjus-robotic-studio** [comment]
But it is a python file

**Comment by sanjus-robotic-studio** [comment]
@geekquad now the algorithm is in the ml folder

**Review by geekquad — APPROVED** [review]

**Pull request merged**
