### PR TITLE
CPP maths : Solution to 3 problems: Find_volume_of_various_shapes.cpp , sum_of_digits.cpp , LCM_of_two_numbers.cpp

### PR DESCRIPTION
**Pull request by mustang519**
I have added the solutions to three problems under cpp maths . 
1.Find volumes of various shapes
2.Sum of digits of 2 numbers.
3.LCM of 2 numbers.

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @mustang519, please use a switch case or something to make it optional for the user. The user should select whether he wants the volume of a cube or cuboid, etc. I hope you get me. If you have any confusion please feel free to contact me on Slack. Thankyou.

**Review by geekquad — APPROVED** [review]

**Comment by mustang519** [comment]
Sure . I'll  add a switch case for  Find_volumes question. When I'm making another PR , do I have to add all the 3 solutions or only the one , where I have to make change. Please clarify.

**Comment by mustang519** [comment]
I have implemented the problem in switch case , and made the changes in this PR. I hope this is okay?

**Comment by mustang519** [comment]
@geekquad I have made the necessary changes already. Please approve this PR if it is good to go . 
If there is any error or modification required please tell me.

**Review by geekquad — APPROVED** [review]

**Comment by mustang519** [comment]
Thank you for approving the PR.

**Pull request merged**
