### PR TITLE
Logistic Regression

### PR DESCRIPTION
**Pull request by Pranjalmishra30**
Added Logistic Regression technique.
Fixes https://github.com/geekquad/AlgoBook/issues/2#issue-709819989

### CODE REVIEW

**Comment by Pranjalmishra30** [comment]
Hey @geekquad please review

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @Pranjalmishra30, please see the path. We asked it specifically that please place it under the respective folders. The folder needs to be in the ML folder. Also, please add a requirements.txt file as well. 
Thank you :)

**Comment by Pranjalmishra30** [comment]
Added the requirements.txt file . Logistic Regression is already in the ML folder. Please have a look

Screenshot from 2020-10-01 14-11-00

**Comment by Pranjalmishra30** [comment]
@geekquad Please Review

**Pull request merged**
