### PR TITLE
Added K means #6

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
## Description
Added implementation of K means Unsupervised Machine Learning Algorithm

## Fixes Issue - #6

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey @geekquad Take a look at this PR.

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @kritikaparmar-programmer, please add a requirements.txt file as well. Also, maybe you can try to do some parameter tuning as well? Do let me know if you have any issues. Thankyou :)

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @kritikaparmar-programmer, Nice work. Can you please perform K-means on a dataset too?

**Comment by kritikaparmar-programmer** [comment]
@geekquad Kindly take a look at changes now..

**Review by geekquad — APPROVED** [review]

**Pull request merged**
