### PR TITLE
Added Scratch Implementation of  Decision Trees

### PR DESCRIPTION
**Pull request by piyushP7pravin**
Implemented Linear Regression Algorithm from scratch on a dummy data
Added Decision Tree Algo

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @piyushP7pravin, amazing work. Please add a requirements.txt file as well. Thankyou :)

**Comment by geekquad** [comment]
Hey @piyushP7pravin, these issues were already assigned to someone else. However, since the assignee of the Decision Tree algorithm pulled back. I can accept it. Please make the changes as asked and delete the Implementation of Linear Regression. Thankyou :)

**Comment by piyushP7pravin** [comment]
> Hey @piyushP7pravin, these issues were already assigned to someone else. However, since the assignee of the Decision Tree algorithm pulled back. I can accept it. Please make the changes as asked and delete the Implementation of Linear Regression. Thankyou :)

@geekquad Done

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @piyushP7pravin, we dont add python in our requirements.txt.
Also the correct way to add libraries is:
```
numpy==1.15.4
```
and not 
```
numpy 1.15.4
```
Please made the necessary changes. Thankyou :)

**Comment by piyushP7pravin** [comment]
> Hey @piyushP7pravin, we dont add python in our requirements.txt.
> Also the correct way to add libraries is:
> 
> ```
> numpy==1.15.4
> ```
> 
> and not
> 
> ```
> numpy 1.15.4
> ```
> 
> Please made the necessary changes. Thankyou :)

@geekquad Updated requirements.txt

**Review by geekquad — APPROVED** [review]

**Pull request merged**
