### PR TITLE
text summarizer

### PR DESCRIPTION
**Pull request by manish2202**
PR for issue #407

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @manish2202, this is not how things are done. 
1. requirements.txt file is not made this way. Please refer to the code section and see how it is made.
2. By pipelining the code, I meant to make a class and then call it. The user should enter the text and get the summarized text as output when called.

**Comment by manish2202** [comment]
Okay. I will be working on it.

**Comment by manish2202** [comment]
> Hey @manish2202, this is not how things are done.
> 
> 1. requirements.txt file is not made this way. Please refer to the code section and see how it is made.
> 2. By pipelining the code, I meant to make a class and then call it. The user should enter the text and get the summarized text as output when called.

I have solved the first part. I am working on creating the class.

**Comment by manish2202** [comment]
> Hey @manish2202, this is not how things are done.
> 
> 1. requirements.txt file is not made this way. Please refer to the code section and see how it is made.
> 2. By pipelining the code, I meant to make a class and then call it. The user should enter the text and get the summarized text as output when called.

Hello, I have changed both the files. Is it okay now?

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @manish2202, I guess you are not able to understand. 
1. I asked you to change the requirements.txt file and remove all the unnecessary packages.
2. I cannot see any cosine similarity function/method/formulation calls in the code.
3. README files are to be written in markdown. They are to be with the extension .md. 

Please look [here](https://github.com/geekquad/StandSum) and see how things are to be done. If you need any help feel free to reach out to me on Slack. Thankyou.

**Pull request closed without merging**
