### PR TITLE
Sorting Algorithms in Python

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Will add more

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
- [x] Insertion Sort
- [x] Selection Sort
- [x] Bubble Sort
- [x] Heap Sort
- [x] Quick Sort
- [x] Radix Sort
- [x] Merge Sort

**Comment by Siddhant-K-code** [comment]
- [x] Iterative Binary Search
- [x] Recursive Binary Search

**Comment by Siddhant-K-code** [comment]
Closing for now, will push it tomorrow

**Comment by geekquad** [comment]
> Closing for now, will push it tomorrow

Sure. Thank you :)
Assigned you with algorithms. Make specific PRs for each. Happy Coding :)

**Pull request closed without merging**
