### PR TITLE
Alexnet Model and Cancer classfier

### PR DESCRIPTION
**Pull request by lavish619**
Added two directories. One contains  cnn alexnet architecture and other contains Brest cancer classifier built on Keras.

### CODE REVIEW

**Review by geekquad — APPROVED** [review]

**Review by geekquad — APPROVED** [review]

**Review by geekquad — APPROVED** [review]

**Review by geekquad — CHANGES_REQUESTED** [review]
Please add Keras in the requirements.txt as well. I think you missed it out by mistake. Rest Super awesome work man.

**Comment by lavish619** [comment]
There are 2 directories actually, The one with alexnet has used keras from Tensorflow directly, separately Keras is not imported, so that's why I haven't put it in that respective Requirements.txt. In the classifier notebook, Keras is used directly so it's there in that requirements.txt

**Comment by lavish619** [comment]
In my laptop, there were version errors between keras and tensorflow, so because of that I removed Keras and used tensorflow only.

**Review by geekquad — APPROVED** [review]

**Comment by geekquad** [comment]
> There are 2 directories actually, The one with alexnet has used keras from Tensorflow directly, separately Keras is not imported, so that's why I haven't put it in that respective Requirements.txt. In the classifier notebook, Keras is used directly so it's there in that requirements.txt

Okay okay. No issues. Great job man.

**Pull request merged**
