### PR TITLE
Adding AlgoBook_Poster to readme_images

### PR DESCRIPTION
**Pull request by arpita-in**

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]
Amazing Poster, Great Work

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Remove `(https://postimg.cc/zVZSkMYT)`

from `[](https://postimg.cc/zVZSkMYT)`

in `README.md`

**Comment by arpita-in** [comment]
@Siddhant-K-code I guess removing (https://postimg.cc/zVZSkMYT) will add the poster twice which is completely redundant.

**Comment by Siddhant-K-code** [comment]
Why Did U Added Clickable link of Picture, You Can Do Simply Like this :

``

Instead of :

`[](https://postimg.cc/zVZSkMYT)`

**Comment by Siddhant-K-code** [comment]
and also why did u added `#poll` in `README.md`

**Comment by arpita-in** [comment]
#poll was added mistakenly. I have updated the link. Just check once.

**Review by Siddhant-K-code — APPROVED** [review]
Perfect !

**Review by geekquad — APPROVED** [review]
Amazing Work @arpita-in. Thank you :)

**Pull request merged**
