### PR TITLE
added dynamic programming algorithms

### PR DESCRIPTION
**Pull request by saileshbro**

### CODE REVIEW

**Comment by saileshbro** [comment]
@geekquad can you review this?

**Comment by geekquad** [comment]
Awesome work @saileshbro. Sorry for the delay.
However, I was not able to get the reference. Please create an issue for the same so that I can get an idea of what you are actually trying to do. 
Please feel free to contact us on our Slack channel. Thankyou :)

**Comment by saileshbro** [comment]
this addresses #128 issue.

**Comment by geekquad** [comment]
Awesome @saileshbro. Thankyou :)

**Pull request merged**
