### PR TITLE
Added 3 Ugly Number files and changed the volume file to .py

### PR DESCRIPTION
**Pull request by Anagha-2000**
Ugly Number: 

1. Program to check whether a number is an UGLY NUMBER
2. Program to print first N UGLY NUMBERS
3. Program to print the Nth UGLY NUMBER

### CODE REVIEW

**Comment by Anagha-2000** [comment]
@geekquad pls review this PR

**Review by geekquad — CHANGES_REQUESTED** [review]
please change the file name to **recursive_bubble_sort**.
The spelling of recursion is incorrect. Thankyou :)

**Comment by Anagha-2000** [comment]
I actually deleted that file. I had to make some changes in the file. Recursive bubble sort is not there in the PR.

@geekquad

**Comment by Anagha-2000** [comment]
@geekquad I have made the change. Please review the PR

**Review by geekquad — APPROVED** [review]

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @Anagha-2000, please changethe path. 
The code should be in **"cpp/sorting"**

**Comment by Anagha-2000** [comment]
Ok sure

**Pull request closed without merging**
